<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST');
if($_POST["City"]!=null&& $_POST["State"]!=null && $_POST["StreetAddress"]!=null)
{
$zillowurl="http://www.zillow.com/webservice/GetDeepSearchResults.htm?zws-id=X1-ZWz1dx849f6f4b_8qndf&address=";
$steet = urlencode(preg_replace('/\s+/', '+',$_GET["StreetAddress"]));
$zillowurl=$zillowurl.$steet;
$zillowurl=$zillowurl."&citystatezip=";
$cit=preg_replace('/\s+/',"+",$_GET["City"]);
$zillowurl=$zillowurl.$cit;
$zillowurl=$zillowurl."%2C+";
$stat=preg_replace('/\s+/',"+",$_GET["State"]);
$zillowurl=$zillowurl.$stat;
$zillowurl=$zillowurl."&rentzestimate=true";
echo("$zillowurl");
$xmlload=new SimpleXmlElement(file_get_contents($zillowurl));
//$xmlload = simplexml_load_file("response.xml");
//print_r($xmlload);
if($xmlload->message->code!=0)
{
$load='{"result":{"code":"789"}}';
echo ($load);
}
else 
{
$load='{"result":';
if(!empty($xmlload->response->results->result))
{
$field=$xmlload->response->results->result;

}
else
{
$field="N/A";
}
if(!empty($xmlload->request))
{
$details=$xmlload->request;

}
else
{
$details="N/A";
}
if(!empty($field->zestimate))
{
$estimate=$field->zestimate;
}
else
{
$estimate="N/A";
}
if(!empty($estimate->valuationRange->low))
{
$valuationlow=number_format((float)$estimate->valuationRange->low,'2','.',',');
}
else
{
$valuationlow="N/A";
}
if(!empty($estimate->valuationRange->high))
{
$valuationhigh=number_format((float)$estimate->valuationRange->high,'2','.',',');
}
else
{
$valuationhigh="N/A";
}
if(!empty($field->rentzestimate))
{
$rentestimate=$field->rentzestimate;
}
else
{
$rentestimate=null;
}
if(!empty($rentestimate->valuationRange->low))
{
$rentvaluationlow=number_format((float)$rentestimate->valuationRange->low,'2','.',',');
}
else
{
$rentvaluationlow="N/A";
}
if(!empty($rentestimate->valuationRange->high))
{
$rentvaluationhigh=number_format((float)$rentestimate->valuationRange->high,'2','.',',');
}
else
{
$rentvaluationhigh="N/A";
}
if(!empty($field->links->homedetails))
{
$links=$field->links->homedetails;

}
else
{
$links="N/A";
}
date_default_timezone_set('America/Los_Angeles');
if(!empty($field->lastSoldDate))
{
$solddate=strtotime($field->lastSoldDate);
}
else
{
$solddate=null;
}
$printdown="http://www-scf.usc.edu/~csci571/2014Spring/hw6/down_r.gif";
$printup="http://www-scf.usc.edu/~csci571/2014Spring/hw6/up_g.gif";
if(!empty($estimate->valueChange))
{
if((float)$estimate->valueChange<0){
$valuechange="-";
$dayschange=str_replace("-","",$estimate->valueChange);
}
else{
$valuechange="+";
$dayschange=str_replace("-","",$estimate->valueChange);
}
}
else
{
$print12="30 Days Overall Change:";
}
if(!empty($solddate))
{
$date=date('d-M-Y',$solddate);
}
else
{
$date="N/A";
}
if(!empty($estimate->{'last-updated'}))
{
$estimatedate=strtotime($estimate->{'last-updated'});
$dateest=date('d-M-Y',$estimatedate);

}
else
{
$dateest="N/A";
}

if(!empty($estimate->{'last-updated'}))
{
$rentupdate=strtotime($rentestimate->{'last-updated'});
}
else
{
$rentupdate="N/A";
}
if(!empty($rentupdate))
{
$rentdate= date('d-M-Y',$rentupdate);
}
else
{
$rentdate="N/A";
}
if(!empty($estimate->amount))
{
$rentest=number_format((float)$estimate->amount,'2','.',',');
}
else
{
$rentest=null;
}
if(!empty($field->lastSoldPrice))
{
$soldprice=number_format((float)$field->lastSoldPrice,'2','.',',');
}
else
{
$soldprice=null;
}
if(!empty($dayschange))
{
$change30=number_format((float)$dayschange,'2','.',',');
}
else
{
$change30=null;
}
if(!empty($rentestimate->valueChange))
{
if((float)$rentestimate->valueChange<0){
$rvaluechange="-";
$rentval=str_replace("-","",$rentestimate->valueChange);
$rent30=number_format((float)$rentval,'2','.',',');
$print23="30 Days Overall Change <img src=\"http://www-scf.usc.edu/~csci571/2014Spring/hw6/down_r.gif\"></img>:";
}
else{
$rvaluechange="+";
$rent30=number_format((float)$rentestimate->valueChange,'2','.',',');
$print23="30 Days Overall Change <img src=\"http://www-scf.usc.edu/~csci571/2014Spring/hw6/up_g.gif\"></img>:";
}

}
else
{
$print23="30 Days";
}
if(!empty($rentestimate->amount))
{
$zestrent=number_format((float)$rentestimate->amount,'2','.',',');
}
else
{
$zestrent=null;
}
if(!empty($field->taxAssessment))
{
$taxass=number_format((float)$field->taxAssessment,'2','.',',');
}
else
{
$taxass=null;
}
if(!empty($soldprice))
{
$print01="\$$soldprice";
}
else
{
$print01="N/A";
}
if(!empty($rentest))
{
$print02="\$$rentest";
}
else
{
$print02="N/A";
}
if(!empty($change30))
{
$print03="\$$change30";
}
else
{
$print03="N/A";
}
if(!empty($zestrent))
{
$print04="\$$zestrent";
}
else
{
$print04="N/A";
}
if(!empty($valuationlow)&&!empty($valuationhigh))
{
$print05="\$$valuationlow-\$$valuationhigh";
}
else
{
$print05="N/A";
}
if(!empty($taxass))
{
$print06="\$$taxass";
}
else
{
$print06="N/A";
}
if(!empty($rentvaluationlow)&&!empty($rentvaluationhigh))
{
$print07="\$$rentvaluationlow-\$$rentvaluationhigh";
}
else
{
$print07="N/A";
}
if(!empty($rent30))
{
$print08="\$$rent30";
}
else
{
$print08="N/A";
}
if(!empty($field->lotSizeSqFt))
{
$print09="$field->lotSizeSqFt sq.ft";
}
else
{
$print09="N/A";
}
if(!empty($field->finishedSqFt))
{
$print10="$field->finishedSqFt sq.ft";
}
else
{
$print10="N/A";
}
$print11=$field->address->street;
$print14=$field->address->city;
$print15=$field->address->state;
$print13=$field->address->zipcode;
if(!empty($field->useCode))
{
$usecode=$field->useCode;
}
else
{
$usecode="N/A";
}
if(!empty($field->yearBuilt))
{
$yearbuilt=$field->yearBuilt;
}
else
{
$yearbuilt="N/A";
}
if(!empty($field->bathrooms))
{
$bathroom=$field->bathrooms;
}
else
{
$bathroom="N/A";
}
if(!empty($field->bedrooms))
{
$bedroom=$field->bedrooms;
}
else
{
$bedroom="N/A";
}
if(!empty($field->taxAssessmentYear))
{
$taxyear=$field->taxAssessmentYear;
}
else
{
$taxyear="N/A";
}
if(!empty($field->taxAssessmentYear))
{
$taxyear=$field->taxAssessmentYear;
}
else
{
$taxyear="N/A";
}
$zipid=$field->zpid;
$zillow="http://www.zillow.com/webservice/GetChart.htm?zws-id=X1-ZWz1dx849f6f4b_8qndf&zpid=";
$zillow.="$zipid";
$zillow.="&unit-type=percent&width=600&height=300&chartDuration=";
$zillowurl1="$zillow"."1year";
$zillowurl5="$zillow"."5years";
$zillowurl10="$zillow"."10years";
$xmlload1=new SimpleXmlElement(file_get_contents($zillowurl1));
$chart1year=$xmlload1->response->url;
$xmlload5=new SimpleXmlElement(file_get_contents($zillowurl5));
$chart5year=$xmlload5->response->url;
$xmlload10=new SimpleXmlElement(file_get_contents($zillowurl10));
$chart10year=$xmlload10->response->url;
$code=$xmlload->message->code;
//echo("$zillowurl11");
$array1=array(
"code"=>"$code",
"homedetails"=>"$links",
"street"=>"$print11",
"city"=>"$print14",
"state"=>"$print15",
"zipcode"=>"$print13",
"useCode"=>"$usecode",
"lastSoldPrice"=>"$print01",
"yearBuilt"=>"$yearbuilt",
"lastSoldDate"=>"$date",
"lotSizeSqFt"=>"$print09",
"estimateLastUpdate"=>"$dateest",
"estimateAmount"=>"$print02",
"finishedSqFt"=>"$print10",
"estimateValueChangeSign"=>"$valuechange",
"imgn"=>"$printdown",
"imgp"=>"$printup",
"estimateValueChange"=>"$print03",
"bathrooms"=>"$bathroom",
"estimateValuationRangeLow"=>"$valuationlow",
"estimateValuationRangeHigh"=>"$valuationhigh",
"bedrooms"=>"$bedroom",
"restimateLastUpdate"=>"$rentdate",
"restimateAmount"=>"$print04",
"taxAssessmentYear"=>"$taxyear",
"restimateValueChangeSign"=>"$rvaluechange",
"restimateValueChange"=>"$print08",
"taxAssessment"=>"$print06",
"restimateValuationRangeLow"=>"$rentvaluationlow",
"restimateValuationRangeHigh"=>"$rentvaluationhigh",
"chart1year"=>"$chart1year",
"chart5year"=>"$chart5year",
"chart10year"=>"$chart10year",
);
$load.=json_encode($array1);
$load.="}";
echo$load;


}
}
?>

